// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACjoarLM6ve8rDAwaKasWih80NTajv-WE',
    appId: '1:965299545949:web:2fae668f9972e7dfd32ab4',
    messagingSenderId: '965299545949',
    projectId: 'lowestpricebabyproduct',
    authDomain: 'lowestpricebabyproduct.firebaseapp.com',
    storageBucket: 'lowestpricebabyproduct.appspot.com',
    measurementId: 'G-G390JEE75R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz9nWKDANFG478vAxecqBwGUaVUlqZZNc',
    appId: '1:965299545949:android:3200080ab19827bfd32ab4',
    messagingSenderId: '965299545949',
    projectId: 'lowestpricebabyproduct',
    storageBucket: 'lowestpricebabyproduct.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBizQkHoq_1gi_GmLZmi-VB61ABTAJHJ6s',
    appId: '1:965299545949:ios:782533cc1e2f7b90d32ab4',
    messagingSenderId: '965299545949',
    projectId: 'lowestpricebabyproduct',
    storageBucket: 'lowestpricebabyproduct.appspot.com',
    iosClientId: '965299545949-inof9emdq6psc9k9ii38ce3jcoj8romd.apps.googleusercontent.com',
    iosBundleId: 'com.tistory.dcsun59.lowestpricebabyproduct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBizQkHoq_1gi_GmLZmi-VB61ABTAJHJ6s',
    appId: '1:965299545949:ios:7411633df6386615d32ab4',
    messagingSenderId: '965299545949',
    projectId: 'lowestpricebabyproduct',
    storageBucket: 'lowestpricebabyproduct.appspot.com',
    iosClientId: '965299545949-2f6qs3mtuojc5itunoivmqa9hdvk59v8.apps.googleusercontent.com',
    iosBundleId: 'com.tistory.dcsun59.lowestpricebabyproduct.RunnerTests',
  );
}
